deepseek-ai/awesome-deepseek-integration

README.md, README_cn.md, docs/huixiangdou/README.md, docs/huixiangdou/README_cn.md
茴香豆是个工作在群聊里的领域知识助手：
1. 支持个人微信、飞书群
2. 专注解答问题，不理会闲聊
3. 幻觉消除到可实用状态，运行半年累计见过 2 次幻觉 corner case
4. 不需要训练，使用算法 pipeline 解决问题。默认配置 deepseek，可泛化到任意知识库
5. 抗攻击能力极强。已面对数千用户运行半年，被真实用户“调戏"了 2w 次未出现价值观问题
见我们的论文  https://arxiv.org/abs/2401.08772 ，我们的卖点是算法 pipeline
和源码地址  https://github.com/InternLM/HuixiangDou
=> feat(app): add huixiangdou

README.md, README_cn.md, docs/enconvo/README.md, docs/enconvo/README_cn.md
Enconvo是AI时代的启动器,是所有AI功能的入口,也是一位体贴的智能助理.
谢谢
=> 添加 enconvo

README.md, README_cn.md, docs/cherrystudio/README.md, docs/cherrystudio/README_cn.md
=> add Cherry Studio Application

README.md
Add Onegai Copilot intellij plugin as deepseek-integration app
=> Update README.md for Onegai Copilot

README.md
=> Update README.md for RSS Translator

README.md, README_cn.md
As an enthusiast for efficient workflow automation, I frequently use n8n, an excellent open-source platform, to build and manage various workflows. n8n boasts a rich set of built-in nodes and community-contributed nodes, making it easy to integrate various services and tools. Recently, I discovered the outstanding AI model DeepSeek, which performs exceptionally well in various benchmark tests. To incorporate the powerful capabilities of DeepSeek into my workflows, I developed a DeepSeek community node for n8n. With this node, I can conveniently invoke DeepSeek models within my workflows to perform various intelligent tasks such as natural language processing, question answering, and text generation.
=> Update README, Add n8n-nodes-deepseek

docs/continue/README.md
We have already released official FIM support.
=> Update Continue.dev README.md

README.md, README_cn.md
Added a new software (Video Subtitle Master) in the README, which integrates support for DeepSeek. Many thanks to DeepSeek for providing excellent services.
=> feat(doc): add software video subtitle master

README.md, README_cn.md
=> fix: cherry studio logo url

docs/avante.nvim/README_cn.md
See [42de893](https://github.com/deepseek-ai/awesome-deepseek-integration/commit/42de8933f182288fbaa34d6515ca3e87da5a796c#diff-af2954e6485dc62deee85b80f9e329a3a3d3968f3f723dbad303bd3c99f9f977R57) and [this](https://github.com/deepseek-ai/awesome-deepseek-integration/pull/48#issuecomment-2523735019)
@jexjws
=> fix: correct typo in avante.nvim

README.md, README_cn.md
添加 Chinese English Translate 插件
=> 添加 Chinese English Translate 插件

README.md, README_cn.md
add Easydict translation application.
it's GitHub URL is https://github.com/tisfeng/Easydict/tree/main
=> add Easydict application

README.md, README_cn.md
Add relative links to integration README
=> minor change on Raycast links

README.md, README_cn.md
项目使用 deepseekv3 + cursor 初始化和迭代，在产品中“字幕纠错”、”AI 自动标题“、“多语言字幕翻译”等功能都可以调用 deepseek 进行处理❤️
=> docs: add LiberSonora

README.md, README_cn.md, docs/immersive_reading_guide/README.md, docs/immersive_reading_guide/README_cn.md
NO Sidebar!!! Immersive AI web summarization, ask questions...
=> Add immersive-reading-guide

README.md
Added a period (.) to complete the sentences in the table and made it consistent with the rest of the other sentences
=> Consistency 

README.md, README_cn.md
A groundbreaking open-source browser translation extension that allows everyone to enjoy a reading experience akin to their native language.
一款革新性的浏览器**开源翻译插件**，让所有人都能够拥有基于母语般的阅读体验。https://fluent.thinkstu.com/
=> add FluentRead browser plugin

README.md, docs/curator/README.md, docs/curator/README_cn.md
[Curator](https://github.com/bespokelabsai/curator): Synthetic Data curation for post-training and structured data extraction
=> feature: add Curator

README.md, README_cn.md
In order to adapt to more application scenarios, we have renamed the QChatGPT project to LangBot and made significant updates. This PR updates the name and description of LangBot.
=> doc: update LangBot (QChatGPT)

docs/codecompanion.nvim/README.md, docs/codecompanion.nvim/README_cn.md
Modify the installation code snippet as codecompanion.nvim now has built-in deepseek support
=> doc: update codecompanion.nvim installation code snippet

README.md, README_cn.md
PapersGPT is a software which is seemlessly integrated with DeepSeek and other multiple cutting-edge AI models for quickly reading papers.
=> Add PapersGPT with DeepSeek

README.md, README_cn.md
=> Add ShellOracle terminal utility to readme

README_cn.md
=> Added Nice Prompt

README.md, README_cn.md
=> add story-flicks

README.md, README_cn.md
=> docs: fix ja README link

README.md, README_cn.md
I forget to change the offical web link....
=> update Ncurator link

README_cn.md
=> fix wrong url in README_cn.md

README.md, README_cn.md, README_ja.md
The README has been updated to include the RssFlow browser extension, which supports DeepSeek.
=> Added a description to the RSSFlow browser extension.

README.md
Portkey is an AI Gateway for fast, reliable & secure routing to 1600+ language, vision, audio, and image models. It is a lightweight, open-source, and enterprise-ready solution that allows you to integrate with any language model in under 2 minutes.
Portkey Integrated with DeepSeek using it's unified API. here are the docs for the same: https://portkey.ai/docs/integrations/llms/deepseek#deepseek
=> Add Portkey AI to 'Others' in Readme.md

README.md, README_cn.md, README_ja.md
Add DeepSearcher, which combines powerful LLMs (DeepSeek, etc.) and Vector Databases (Milvus, etc.) to perform search, evaluation, and reasoning based on private data, providing highly accurate answer and comprehensive report.
=> Add DeepSearcher

README.md
smolagents is the repo for building great agents with open models like DeepSeek-R1.
And it has strong traction: we gained ~10k GitHub stars over the last month.
Read more here! https://github.com/huggingface/smolagents
=> Add smolagents!

README.md, README_cn.md, README_ja.md
- add AI Commit to the list of VS Code extensions in README, README_cn, and README_ja
=> 📝 docs(README): add AI Commit to VS Code extension list

README.md, README_cn.md, README_ja.md
This PR updates the documentation to better organize and clarify the AI code editor section in the README files. The changes include:
- Renamed the "Cursor" section to "Native AI Code Editor" to better categorize AI-powered code editors
- Added a direct link to Cursor's website for easier access
- Updated the description to clarify Cursor's relationship with VS Code
- Made corresponding updates in all language versions (English, Chinese, and Japanese)
This change improves the documentation by:
- Using more precise categorization for AI-powered development tools
- Making it easier for users to find and access the referenced tools
- Maintaining consistency across all language versions
- README.md
- README_cn.md
- README_ja.md
=> docs: update README files with native AI code editor section

README.md, README_cn.md, README_ja.md
你好，我是Trancy 的作者，来自中国的开发团队。Trancy 是一款类似于沉浸式翻译的扩展，但拥有更多的功能，如AI划句翻译，单词精准翻译，Youtube双语字幕翻译，Trancy 刚刚支持你Deepseek 的接入，用户可以自定义添加。 希望通过PR，让Trancy可以帮助到更多的用户。
=> Add Trancy

README.md, README_cn.md, README_ja.md
项目：  https://github.com/wangrongding/wechat-bot
集成了 deepseek 等一系列 ai 服务
目前 star 数： 6.5k ⭐️
=> add Wechat-Bot entry to README files

README.md
Adds Cliprun - a Chrome extension that integrates with DeepSeek. Thanks!
=> Add Cliprun

README.md, README_cn.md, README_ja.md
the README.md at https://github.com/titusTong/seekCodeCopilot/blob/main/README.md
=> aad vscode extensions

README.md, README_cn.md, README_ja.md
DeepChat is a fully free desktop smart assistant, with a powerful DeepSeek large model, supporting multi-round conversations, internet search, file uploads, knowledge bases, and more.
https://github.com/ThinkInAIXYZ/deepchat
Apache license 2.0
=> Add DeepChat application

README.md, README_cn.md, README_ja.md
=> fix: broken link

README.md
[Simplismart](https://www.simplismart.ai/) is the fastest inference for LLMs, Diffusion, and Speech models. Deploy Deepseek effortlessly on the Simplismart Cloud or with your own Cloud.
=> Added Simplismart AI

README.md, README_cn.md, README_ja.md
- Add Siri Ultra which have 1000 stars on Github
- Support internet connectivity and multi-turn conversations
- Integrate with DeepSeek series models
=> feat: add Siri Ultra shortcut integration

README.md, README_cn.md, README_ja.md
Hello, I would like to submit my project
Askanywhere is a learning tool that can select text anywhere and start a conversation with Deepseek. Used for quickly querying concepts, answering questions, suggesting text modifications, etc., with the ability to intelligently recognize operational intent based on selected text.
THANK YOU!
=> Add Askanywhere to awesome deepseek list

README.md, README_cn.md, README_ja.md
1chat is an open-source iOS app that runs the DeepSeek model locally.
Github repository:
[https://github.com/OJZen/1chat](https://github.com/OJZen/1chat)
=> Add: 1chat. An open-source iOS app that runs the DeepSeek model locally.

README.md, README_cn.md, README_ja.md
dingo is A Comprehensive Data Quality Evaluation Tool.  It already supports deepseek to eval data quality. Quick try in hf: https://huggingface.co/spaces/DataEval/dingo.
=> [feat]: add dataeval/dingo tool

README.md
<table align="center">
<tr>
<th>Vendor</th>
<th>Model</th>
</tr>
<tr>
<td align="center">DeepSeek</td>
<td>
<code>deepseek-chat</code> <code>deepseek-reasoner</code> <code>deepseek-coder</code>
</td>
</tr>
<tr>
<td align="center">百度</td>
<td>
<code>ernie-lite-8k</code> <code>ernie-tiny-8k</code> <code>ernie-speed-8k</code> <code>ernie-speed-128k</code> <code>deepseek-v3</code> <code>deepseek-r1</code>
</td>
</tr>
<tr>
<td align="center">阿里巴巴</td>
<td>
<code>deepseek-v3</code> <code>deepseek-r1</code> <code>deepseek-r1-distill-qwen-1.5b</code> <code>deepseek-r1-distill-qwen-7b</code> <code>deepseek-r1-distill-qwen-14b</code> <code>deepseek-r1-distill-qwen-32b</code>
</td>
</tr>
<tr>
<td align="center">讯飞</td>
<td>
<code>lite</code> <code>generalv3</code> <code>pro-128k</code> …
=> Add: chatchat python pacakge, A Large Language Models Python API

README.md, README_cn.md, README_ja.md, docs/docky-ai/README.md, docs/docky-ai/README_cn.md, docs/docky-ai/README_ja.md
[Docky AI](https://docky.ai) is a powerful browser extension that allows you to have real-time conversations with multiple AI models through a sidebar. It supports simultaneous communication with multiple models and can assist you in reading web pages, writing, translating, and creating images
=> add Docky AI

README.md, README_cn.md, README_es.md, README_ja.md, README_zh_tw.md
尊敬的维护者，
您好！此 PR 是为了支持更多其他语言信息，在 awesome-deepseek-integration 的文档中添加繁体中文以及西班牙语，语言均已翻译完善
感谢您考虑我的请求，期待您的反馈！
此致，
敬礼
=> Add other languages

README.md
Update the image source for SerpApi to an absolute path.
Thank you very much for merging the previous PR!
=> Fix image src for SerpApi

README.md, README_cn.md, README_es.md, README_ja.md, README_zh_tw.md
This PR adds LawAgent to the application section. LawAgent a legal AI product developed by the Tensorbounce team,   combines a comprehensive legal knowledge base with AI Agent capabilities, offering powerful tools for legal analysis, contract review, document generation, file translation, and more.
- Custom Legal Knowledge Base: Allows users to create and configure personalized legal knowledge bases tailored to specific needs.
- Professional Analysis Mode: Powered by DeepSeek-R1, enabling advanced reasoning and analysis for complex legal scenarios.
- Web-Based Knowledge Base Import: Supports importing knowledge bases directly from web sources for seamless integration.
- Intelligent Q&A with Citations: Provides AI-driven question answering with references to the knowledge base for accuracy …
=> feat: add LawAgent to the  Application section

README_cn.md
添加一个Office插件项目"OfficeAI助手"。
OfficeAI助手是一款免费的办公插件，通过接入大模型的能力，在Office中提供AI问答、AI校对、AI排版、AI创作、AI数据处理等功能。它支持接入DeepSeek、ChatGPT等主流AI模型平台，兼容Microsoft Office和WPS Office。
=> Add OfficeAI助手

README.md
添加 "OfficeAI助手" 英文版介绍。
OfficeAI Assistant is a free office plugin. By integrating the capabilities of large language models, it provides functions such as AI Q&A, AI proofreading, AI typesetting, AI creation, and AI data processing within Office. It supports connection to mainstream AI model platforms such as DeepSeek and ChatGPT, and is compatible with both Microsoft Office and WPS Office.
=> Add OfficeAI Assistant in en 

README.md, README_cn.md, README_es.md, README_ja.md, README_zh_tw.md
Multi platform networking DeepSeek
Relying on DeepSeek official&Alibaba Cloud&Tiktok Volcano, three channel AI engine, continue to evolve intelligence. And use a combination of "internet search+deep thinking" mode.
-------------------------------
多平台联网DeepSeek
依托DeepSeek官方&阿里云&抖音火山,三通道AI引擎,持续进化智能。并且混合使用“联网搜索+深度思考”模式。
https://wwtl.lanzouv.com/b05fmred
=> Add DeepSeek new integration

README.md, README_cn.md, README_es.md, README_ja.md, README_zh_tw.md
telegram-deepseek-bot提供了一个使用 Golang 构建的 Telegram 机器人，集成了 DeepSeek API，能够提供 AI 驱动的智能回复。该机器人支持 流式响应，使交互更自然和动态。
可以通过不同的命令调用deepseek接口，获取答案或者账号信息，并且集成火山引擎deepseek
=> Add telegram-deepseek-bot

README.md, README_cn.md
- Change GitHub repository link to official website URL (alphabot.x-pai.com)
=> docs: update AlphaBot link to official website

README.md, README_cn.md, README_es.md, README_ja.md, README_zh_tw.md
Add `nlsh`: https://github.com/eqld/nlsh.
NLSH is an AI-powered CLI tool to generate context-aware shell commands with multi-backend LLM support. Supports shell-specific syntax, read-only system tools, and custom inference endpoints.
=> Add `nlsh`

README.md, README_cn.md, README_es.md, README_ja.md, README_zh_tw.md, docs/SwiftChat/README.md, docs/SwiftChat/README_cn.md
1. Fix Chinese documentation link errors in Swift Chat
2. Update Swift Chat features
=> docs: update SwiftChat

README.md
fix readme.md incorrect line breaks
=> docs: fix readme.md incorrect line breaks

README.md, README_cn.md, README_zh_tw.md
=> fix migo url

README.md, README_cn.md
一个脱胎于 Nonebot 插件的由沙盒驱动的独立 Agent 框架，其核心是通过强大灵活的提示词构建系统，引导 AI 生成代码并在安全的沙盒环境中执行。它通过原生的多平台适配器架构实现了强大的跨平台事件流处理能力，能够无缝支持 OneBot v11 (QQ)、Discord、Minecraft 和 B站直播(驱动VTB进行演出) 等多种主流平台。项目还拥有高度可扩展的插件系统、人设与插件共享生态，并支持在复杂的群聊多人交互场景中进行高效互动。目标是为用户和开发者提供极致高效、高自由度与易用性的开发友好型智能中枢。
项目地址：[Nekro Agent](https://github.com/KroMiose/nekro-agent)
=> Add IM Application Plugins: NekroAgent —— 高扩展型的沙盒 Agent 机器人框架

README.md, README_cn.md, README_es.md, README_ja.md, README_zh_tw.md
Adding [God Tier Prompts](https://www.godtierprompts.com) to the tools list.
A new AI prompt leaderboard, where everyone shares their prompts and the best rise to the top.
=> Add new tool to the list

README.md
分别是：
1.STranslate
2.YoMo
3.Autoflow
4.FluentRead
5.Continue
6.AutoDev 
7.Onegai Copilot
8.AI Git Commit
9.Cursor
=> 修复了STranslate、YoMo等9款工具的图标显示问题❤️
