- README.md
- README_cn.md
- docs/ragflow/README.md
- docs/ragflow/README_cn.md
RAGFlow: https://github.com/infiniflow/ragflow, An open source RAG engine which default LLM is DeepSeek-V2. I would like to add it to deepseek integration repo.
> Add RAGFlow

- docs/continue/README.md
Because the apiKey key value is misspelled, it causes authentication failure when using the plugin. #20
> Update continue README.md

- README.md
- README_cn.md
完成部署后，在 `data/config/provider.json` 中填写 DeepSeek 的 api_key，再设置model为`deepseek-chat`，重启即可使用
> doc: add QChatGPT

- docs/deepspace/README.md
- docs/deepspace/README_cn.md
DeepSpace（深度空间）是一款用于调试 DeepSeek API 的工具，由社区制作，灵感来源于 [MoonPalace](https://github.com/MoonshotAI/moonpalace?tab=readme-ov-file)。
**特性**
全平台支持：Mac、Windows、Linux
简单易用：启动后只需将 `base_url` 替换为 `http://localhost:9988` 即可开始调试。
捕获完整请求：包括网络错误时的“事故现场”。
快速检索：通过 `request_id`、`chatcmpl_id` 快速检索、查看请求信息。
报告导出：一键导出 BadCase 结构化上报数据，帮助 DeepSeek 完善模型能力。
> 添加api调试工具：DeepSpace

- README.md
Hi @berry-13 @Kurama622 
This PR adds LiteLLM integration to the deepseek docs. You can see our documentation [here](https://docs.litellm.ai/docs/providers/deepseek). 
We recently added deepseek r-1 support as well - https://github.com/BerriAI/litellm/issues/7877#issuecomment-2608261249
> Update README.md - Add LiteLLM integration

- README.md
Mem0 now support Deepseek as an LLM provider!
Doc: https://docs.mem0.ai/components/llms/models/deepseek
> Docs: Add Mem0

- README.md
Add new section for Emacs, with two integrations that support DeepSeek:
(This is a replacement for PR #100, as the links are not correct in that PR and I think Emacs can have it's own section :))
> Add Emacs section - add `gptel` and `minuet-ai`

- README.md
Geneplore AI runs one of the largest AI-focused bots on Discord, now including Deepseek v3 and R1 from the Deepseek API Platform.
I am currently the head developer over at Geneplore AI, and we just pushed out v4.9.1, which now features two Deepseek models in our collection of the most powerful AI chat models.
> Add Geneplore AI's Discord bot to "Others"

- README.md
- docs/Geneplore AI/README.md
I created a new category called Discord Bots, where Geneplore AI now lives. I also added a folder in docs/ for Geneplore AI, and the link now goes to there.
> Move Geneplore AI listing to its own category, add docs

- README.md
- README_cn.md
- docs/continue/README.md
- docs/continue/README_cn.md
The current Continue's logo is updated in
<https://github.com/continuedev/continue/pull/1227/files>. In this commit, update the Continue's logo img link to the Continue's official git repo link:
<https://github.com/continuedev/continue/blob/main/docs/static/img/logo.png?raw=true>.
Meanwhile, add a missing LF character to the end of README.md that uses LF as the end-of-line character.
> Update Continue's logo img link to the current version

- README.md
- README_cn.md
Add [hustcer/deepseek-review](https://github.com/hustcer/deepseek-review) for code reviews with DeepSeek. It works seamlessly both locally and in GitHub Actions.
Review example: https://github.com/hustcer/deepseek-review/pull/17
- Automate PR Reviews with Deepseek via GitHub Action
- Review Remote GitHub PRs Directly from Your Local CLI
- Analyze Commit Changes with Deepseek for Any Local Repository with CLI
- Fully Customizable: Choose Models, Base URLs, and Prompts
- Supports Self-Hosted Deepseek Models for Enhanced Flexibility
- Add `skip cr` or `skip review` to PR title or body to disable code review in GitHub Actions
- Cross-platform Support: Compatible with GitHub Runners across `macOS`, `Ubuntu`, and `Windows`
> Add hustcer/deepseek-review for code review locally or in GitHub Actions

- README.md
Previously the solana-agent-kit URL was pointing to [RAGFlow Readme](https://github.com/deepseek-ai/awesome-deepseek-integration/blob/main/docs/ragflow/README.md):
I have made the following changes, so that the hyperlink in the readme, points to the correct docs:
- added hyperlink that points to the correct solana-agent-kit [readme file](https://github.com/deepseek-ai/awesome-deepseek-integration/blob/main/docs/solana-agent-kit/README.md) and not RAG.
> updated solana-agent-kit hyperlink

- README.md
the link for solana framework was wrong and its been updated to the correct one.
> Solana framework link updated

- README.md
表格的图标尺寸太小，无法看清。
为了保持统一修改为统一的图标大小。
> pref:   Optimize table avatar column width

- README.md
origin bad url seems from markdown and just fixes it:
```html
<td> <a href="https://rig.rs/)](https://rig.rs/">RIG</a> </td>
```
> Correct href for rig

- docs/continue/README.md
I have tried to use deepseek api in continue (the extension of VSCode which helps to code with AI). 
It seems that the config.json code block show different "provider" value compared to the picture that below the code block. 
I have tried both. **"provider": "openai"** works for me. So I think the "provider" in code block needs to be amended.
> Update the config.json of the 'continue' integration

- README.md
- README_cn.md
- README_ja.md
Hi! I'd like to propose adding our project KAG to the awesome-deepseek list.
KAG is a logical reasoning and Q&A framework based on the [OpenSPG](https://github.com/OpenSPG/openspg) engine and large language models, which is used to build logical reasoning and Q&A solutions for vertical domain knowledge bases.  KAG can effectively overcome the ambiguity of traditional RAG vector similarity calculation and the noise problem of GraphRAG introduced by OpenIE.  KAG supports logical reasoning and multi-hop fact Q&A, etc., and is significantly better than the current SOTA method.
The goal of KAG is to build a knowledge-enhanced LLM service framework in professional domains, supporting logical reasoning, factual Q&A, etc. KAG fully integrates the logical and factual characteristics of the KGs. …
> feat(common): add KAG to the awesome-deepseek list

- README.md
~~Remove Zotero entry from the list~~
~~It literally has nothing to do with deepseek.~~
~~It makes sense to have `PapersGPT` in the list, but not `Zotero`.~~
I realized Zotero has a deepseek integration. I think it should be mentioned in the list, otherwise Zotero looks quite unrelated.
> Update zotero entry

- README.md
- README_cn.md
- README_es.md
- README_ja.md
- README_zh_tw.md
1. [Pot](https://github.com/pot-app/pot-desktop)是一个跨平台的划词翻译和OCR软件，可以调用DeepSeek API或Ollama中的DeepSeek翻译；
2. [Comment Translation](https://github.com/intellism/vscode-comment-translate)是vscode 注释翻译插件, 不干扰正常代码，方便快速阅读源码。可以接入DeepSeek API来进行翻译；
3. [PDFMathTranslate](https://github.com/Byaidu/PDFMathTranslate)是一款基于 AI 完整保留排版的 PDF 文档全文双语翻译工具，可以调用DeepSeek API对论文进行翻译；
4. [哔哩助理](https://github.com/Richasy/Bili.Copilot)是一款B站第三方 Windows 桌面客户端，使用 Windows App SDK 构建的原生应用。
希望能做一点贡献❤️🥺🎈
> 添加四款可以调用DeepSeek的软件或插件

- README.md
- README_cn.md
- README_ja.md
AstrBot is a user-friendly LLM-based multi-platform chatbot with a WebUI, supporting long-term-memory, RAG, LLM agents, and plugins integration.
Repo: https://github.com/Soulter/AstrBot
Related docs: 
- [Integrating with Ollama to use DeepSeek-R1](https://astrbot.app/config/providers/provider-ollama.html#%E6%8E%A5%E5%85%A5-ollama-%E4%BD%BF%E7%94%A8-deepseek-r1-%E7%AD%89%E6%A8%A1%E5%9E%8B)
- [Integrating with LM Studio to use DeepSeek-R1](https://astrbot.app/config/providers/provider-lmstudio.html#%E6%8E%A5%E5%85%A5-lm-studio-%E4%BD%BF%E7%94%A8-deepseek-r1-%E7%AD%89%E6%A8%A1%E5%9E%8B)
- [Integrating with DeepSeek official API to use DeepSeek models](https://astrbot.app/others/provider.html#deepseek)
> docs: Add AstrBot into integration

- README.md
`deepseek-go` is a client library completely supports all the API features (including the beta features) of the Deepseek API. It's the most used deepseek client for go at the moment. The repository also has comprehensive tests that covers almost every feature that's present in the API. Plus it has with external features like JSON mode that's unique to the library which can help with beta features such as chat prefix completion.
Link: https://github.com/cohesion-org/deepseek-go
> Add: deepseek-go. A highly active client for deepseek written in Go. 

- docs/avante.nvim/README.md
Otherwise an error message is returned in the response that the max_tokens must be in the range of `[1, 8192]`. Apparently this property has been raised over this limit in the openai config, which this setup inherits from.
> sets max_tokens avante.nvim/README.md
